services:
  backend:
    image: mikechatzis/hackatumtsichallenge:backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  scenariorunner:
    image: mikechatzis/hackatumtsichallenge:scenariorunner
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tsi
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tsi"]
      interval: 5s
      timeout: 5s
      retries: 5
  frontend:
    image: mikechatzis/hackatumtsichallenge:frontend
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      backend:
        condition: service_started

networks:
  default:
    driver: bridge