name: hackatumenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - flask=2.3.3
  - python-dotenv=1.0.0
  - pip:
    - Flask-SQLAlchemy==3.1.1
    - requests
# pip freeze > requirements.txt